### ISSUE TITLE
Gravity

### ISSUE THREAD

**Issue by FunnyDevs** [Muddz/StyleableToast#10]
Is possible to set toast gravity???

**Comment by hshrimali** [comment]
Yes definitely @FunnyDevs , it is possible and for that I have sent the PR but it was closed by Muddz as he doesn't want to overflow his library with features that aren't important. So, you better work on some other issue I think.

**Comment by rayliverified** [comment]
Haha, toast gravity would be nice feature to have ;)

**Comment by Muddz** [comment]
@FunnyDevs  @hshrimali @searchy2 

You can now change the `Gravity` of the `StyleableToast` by calling `getStyleableToast().setGravity()`

**Comment by hananeboussari** [comment]
can one on top of that happened to make changes to offet x and y as do the setGravity method of android toast.
This method has two more parameters to move the toast, your method has just the gravity if you want to put it down, up or in the middle, but not in a specific place

**Comment by losocarrat** [comment]
> @FunnyDevs @hshrimali @searchy2
> 
> You can now change the `Gravity` of the `StyleableToast` by calling `getStyleableToast().setGravity()`

Hello Mudzz!

Congratulations on your work. I have a doubt:

In my project, this works perfectly in kotlin:

StyleableToast.makeText(baseContext, getString(R.string.toastverde), R.style.verdeToast).show()

I can't make your proposal work:  e.g.    getStyleableToast().setGravity(Gravity.CENTER, 0, 0)

How would you do it?

Thank you very much in advance!

**Comment by Muddz** [comment]
That is because you can't set the X and Y coordinates for StyleableToast.
You can only use Gravity.BOTTOM or Gravity.TOP for other positions than center

**Comment by Muddz** [comment]
> > @FunnyDevs @hshrimali @searchy2
> > You can now change the `Gravity` of the `StyleableToast` by calling `getStyleableToast().setGravity()`
> 
> Hello Mudzz!
> 
> Congratulations on your work. I have a doubt:
> 
> In my project, this works perfectly in kotlin:
> 
> StyleableToast.makeText(baseContext, getString(R.string.toastverde), R.style.verdeToast).show()
> 
> I can't make your proposal work: e.g. getStyleableToast().setGravity(Gravity.CENTER, 0, 0)
> 
> How would you do it?
> 
> Thank you very much in advance!

 That is because you can't set the X and Y coordinates for StyleableToast.
You can only use Gravity.BOTTOM or Gravity.TOP for other positions than center

**Comment by losocarrat** [comment]
> That is because you can't set the X and Y coordinates for StyleableToast.
> You can only use Gravity.BOTTOM or Gravity.TOP for other positions than center

Thank you very much for your quick response. Sorry for my awkwardness :)
I'm going to try it.
