### ISSUE TITLE
Character limit?

### ISSUE THREAD

**Issue by martymiller** [Muddz/StyleableToast#12]
Is there a character limit on toasts?

**Comment by Muddz** [comment]
Sort of. There is `textView.setMaxLines(2);` on the `TextView` showing the Toast text

**Comment by martymiller** [comment]
I assume you had a reason for that.  Does it screw up the layout if there are more than two?

**Comment by Muddz** [comment]
@martymiller As I remember there was no specific reason. Maybe I should raise the number to whatever the default Android Toast allows. Thanks for the notice

**Comment by Muddz** [comment]
@martymiller new update out in version 1.0.9. Limit is now set to 4 lines
