### ISSUE TITLE
is no update textValue size?

### ISSUE THREAD

**Issue by zengcanxiang** [Muddz/StyleableToast#13]

**Comment by Muddz** [comment]
Are you asking if its possible to change the textSize?

**Comment by zengcanxiang** [comment]
Yes. I found that in some cases, the font is too big

**Comment by Muddz** [comment]
The font is the same size as the standard Android Toast. Could you send a screenshot?

**Comment by zengcanxiang** [comment]
Thank you for the answer.   
I copied the sample code md, did not notice the use of `withBoldText ()`.   
Causing the font to be bold, and it looks like it is necessary to resize the font
