### ISSUE TITLE
Protected instead of private?

### ISSUE THREAD

**Issue by ericmguimaraes** [Muddz/StyleableToast#15]
I would like to be able to extend your class and add some methods to modify specific behavior or attributes of some elements. In my case I need to change the gravity of the toast (`toast.setGravity(Gravity.TOP|Gravity.LEFT, 0, 0);`). Is there any way to do that? 
I think would need to have access at least to the `getToastLayout()` method. For now I will probably try to copy your entire class into my project, but I think it would be good to have more flexibility, wouldn't it?

**Comment by Muddz** [comment]
Hi. Yes it would! I'm planning on rebuilding the structure of the code in the next few days and will have that in my mind

**Comment by ericmguimaraes** [comment]
Cool! Thank you for your lib, it looks great!

**Comment by Muddz** [comment]
A new assessor `getStyleableToast()` has been added in the next update. Will be available today!
