### ISSUE TITLE
Icon padding Problem in RTL Languages

### ISSUE THREAD

**Issue by AlirezaHafez** [Muddz/StyleableToast#16]
Hi,
In RTL Languages (Hebrew,Arabic,Persian,...) there is a bug with icon,relative positioning is working and the icon goes to the right side(which is a valid behavior) ,but when it goes to the right side of the Toast there is no padding for the icon and icon sticking to the edge of the right side of the toast.

Good work,your library is the best!

**Comment by Muddz** [comment]
Hi. Thanks for the notice. I'm currently rebuilding and bug fixing alot of stuff and will also try to fix that too. An new update should come up soon

**Comment by Muddz** [comment]
This is now supported and a update will soon be available.
