### ISSUE TITLE
How can change direction

### ISSUE THREAD

**Issue by samanzamani** [Muddz/StyleableToast#17]
Hi
I try add icon to toast with some text . how can move icon to right for right to left language.

**Comment by Muddz** [comment]
Hi Sir. Currently the icon will move to the right side of the toast if you use a RTL language as Arabic, but its not possible to place the icon manually on any side YET!

Next update will include `setIconRight()` and `setIconLeft()`

**Comment by samanzamani** [comment]
Thanks for the answer but i use Farsi language that is a right to left language but icon still display in left side.(test in device with SDK 25)

**Comment by Muddz** [comment]
I will look into it and  solve it in the next update
