### ISSUE TITLE
Icon Layering Issue

### ISSUE THREAD

**Issue by GitUser4732** [Muddz/StyleableToast#19]
Hello,
I am having a issue where the icon is appearing behind the toast on some instances.
The code for each is the same besides the icon and the text.
Any Idea what the issue is?

Toast For Home Nav Clicked(Top)
`StyleableToast st = new StyleableToast
                                            .Builder(MainActivity.this)
                                            .text("Home Nav Clicked")
                                            .textColor(Color.WHITE)
                                            .backgroundColor(ContextCompat.getColor(MainActivity.this, R.color.colorAccent))
                                            .icon(R.drawable.ic_tab_home)
                                            .build();
                                    st.show();`

Toast For Add New Post(Bottom)
`StyleableToast st = new StyleableToast 
                        .Builder(MainActivity.this)
                        .text(fabButtonResult())
                        .textColor(Color.WHITE)
                        .backgroundColor(ContextCompat.getColor(MainActivity.this, R.color.colorAccent))
                       .icon(R.drawable.ic_fab_add_message)
                        .build();
                st.show();`

![layeringissue](https://user-images.githubusercontent.com/30483593/28998272-57dbb19e-79ec-11e7-95a4-37203bdade10.png)

**Comment by GitUser4732** [comment]
Issue seemed to have resolved itself.

**Comment by Muddz** [comment]
Hi and thanks for the notice. The library will soon get a fresh update with bug fixing and new features, improvement! So keep reporting any thing that dosen't work well

**Comment by GitUser4732** [comment]
This issue has returned.

**Comment by GitUser4732** [comment]
Okay, I found the problem. The issue is not related to StyleableToast. I am using the same icon in a TabLayout and didnt call mutate() when altering the color filter.
