### ISSUE TITLE
lineSpacingExtra and textSize for the text

### ISSUE THREAD

**Issue by iad24** [Muddz/StyleableToast#22]
Setting **lineSpacingExtra** and **textSize** in style does not work. Can include this?

`<style name="ToastNormal">
        <item name="android:textColor">@android:color/white</item>
        <item name="android:textSize">30sp</item>
        <item name="android:lineSpacingExtra">8dp</item>
        <item name="android:fontFamily">fonts/GOTHAM-BOOK.ttf</item>
        <item name="android:colorBackground">@color/colorAccent2</item>
    </style>`

**Comment by Muddz** [comment]
Hi. Textsize is now possible in version `2.0.0`

**Comment by iad24** [comment]
@Muddz how bout lineSpacing?

**Comment by Muddz** [comment]
That won't happend for now
