### ISSUE TITLE
How to set duration ?

### ISSUE THREAD

**Issue by Midhilaj** [Muddz/StyleableToast#28]
Like this 
Toast.makeText(mContext,"message",Toast.LENGTH_LONG).show();

**Comment by tcqq** [comment]
new StyleableToast
                .Builder(this)
                .text(error)
                .textColor(android.graphics.Color.WHITE)
                .backgroundColor(ColorUtil.getColor(this, R.color.colorRedDark))
                .length(Toast.LENGTH_LONG)
                .show();

**Comment by Muddz** [comment]
@Midhilaj @tcqq 

**Example of using durations: in a xml style with static constructor**

with `mytoast` in styles.xml you can set the proporty:
 `<item name="length">LONG</item>`

and then pass that style into the constructor 
`StyleableToast.makeText(context, "Hello World!", R.style.mytoast).show();`

Or pass the duration directly in the constructor

`StyleableToast.makeText(context, "Hello World!", LENGTH_LONG, R.style.mytoast).show();`
