### ISSUE TITLE
Attribute "radius" already defined with incompatible format.

### ISSUE THREAD

**Issue by wheat7** [Muddz/StyleableToast#31]
Hello guy, Is "radius" attribute conflict with some library?

**Comment by Muddz** [comment]
Hi! I will look into it.

Could you post the libraries you use and the XML toast style

Den ons. 30. maj 2018 kl. 05.44 skrev Wheat7 <notifications@github.com>:

**Comment by wheat7** [comment]
I found the problem，that  it conflict with with my a library, i had renamed my library "radius" attribute, by the way, i suggest you rename your "radius" attribute to a specially name，otherwise，it is may be conflict with another library. Thank you !

**Comment by Muddz** [comment]
It will be renamed to `cornerRadius`

**Comment by wheat7** [comment]
cool

**Comment by wheat7** [comment]
Cool

**Comment by Muddz** [comment]
@wheat7 Hi again. What format did you use in your own library for attribute `radius` ? I'm trying to reproduce the issue and fail-test it

**Comment by wheat7** [comment]
It is dimension format.
