### ISSUE TITLE
How download this library 

### ISSUE THREAD

**Issue by 01HeLLBoY92** [Muddz/StyleableToast#32]
Where to find the jar file. Help me please:relaxed:

**Comment by Muddz** [comment]
Hi. It is clearly stated in the Installation part of the Readme how to install it. There is no jar file or the need for a jar file for installation of this library

**Comment by 01HeLLBoY92** [comment]
@Muddz Gives an error message "Unknown dependency"

**Comment by Muddz** [comment]
Could you post or screenshot your gradle file

**Comment by Muddz** [comment]
Could you post or screenshot your gradle file

Den ons. 20. jun. 2018 kl. 07.28 skrev 01HeLLBoY92 <notifications@github.com
