### ISSUE TITLE
Compatibility issue with android 8.1

### ISSUE THREAD

**Issue by SamihElsakhawi** [Muddz/StyleableToast#34]
Hi,

Thanks for your tool, i'm using it on project with android 8.0.

But i started to work on a project with android 8.1

Will StyleableToast be compatible with android 8.1 ?

Thank you.

Regards, Sam.

**Comment by Muddz** [comment]
Hi. Yes it should. There is support for the new Toast in Android Oreo. If
it's not working then please just make a new issue
