### ISSUE TITLE
Does this Library Support WebP Image Drawable?

### ISSUE THREAD

**Issue by rk8339811** [Muddz/StyleableToast#35]
I am planning to use this awesome and useful library in my Android App. But does it support WebP format images? Also what would be the best suitable size of the drawable as the normal png image is not so clear while appearing in the Toast.

**Comment by Muddz** [comment]
There is no specific format supported. The icon is just set as a TextView
Drawable from the provided resource Id. There is no suituable size of the
drawable. The best you can do is use an SVG. No matter the size of the
image, it will only be as big as 19dp which is the largest size the icon
can be in the toast.

Den ons. 18. jul. 2018 kl. 16.42 skrev rk8339811 <notifications@github.com>:

**Comment by rk8339811** [comment]
@Muddz   Thank You very much for the clarification and this awesome library.
