### ISSUE TITLE
problem with androidX

### ISSUE THREAD

**Issue by samanzamani** [Muddz/StyleableToast#37]
`StyleableToast` doesn't work with `androidX` library.

**Comment by Muddz** [comment]
Hi. Can you tell me what is not working so I can reproduce it and fix it?

**Comment by samanzamani** [comment]
Hi
first thanks for your great library
after update my application and change all `android.supportlibrary` to `adnroidX` when try to make toast with `StyleableToast` application crush and get this error:
``` 
java.lang.NoClassDefFoundError: Failed resolution of: Landroid/support/v4/content/ContextCompat;
        at com.muddzdev.styleabletoastlibrary.StyleableToast.loadShapeAttributes(StyleableToast.java:227)
        at com.muddzdev.styleabletoastlibrary.StyleableToast.makeShape(StyleableToast.java:135)
        at com.muddzdev.styleabletoastlibrary.StyleableToast.initStyleableToast(StyleableToast.java:107)
        at com.muddzdev.styleabletoastlibrary.StyleableToast.show(StyleableToast.java:118)
```

**code:**
```kotlin
StyleableToast.makeText(this,"Hi", Toast.LENGTH_SHORT,R.style.AlertToast).show()
```

and my **style**:

```
 <style name="AlertToast">
    <item name="textBold">true</item>
    <item name="textColor">#fff</item>
    <item name="textSize">18dp</item>
    <item name="colorBackground">#000</item>
    <item name="solidBackground">true</item>
    <item name="strokeWidth">1dp</item>
    <item name="strokeColor">#fff</item>
    <item name="iconEnd">@drawable/ic_warning</item>
    <item name="radius">5dp</item>
  </style>
```

**Comment by Muddz** [comment]
@samanzamani  Thank you. I will look into it

**Comment by Muddz** [comment]
Hi. I have looked into it in a clean project which only use `androidx` imports and `StyleableToast` worked fine even when it still was on the old `àndroid.support` libraries.

Here is my test project in which I tested it: https://drive.google.com/file/d/1iga9-uKJ3BAIJpkofCBT11bYGMtCRKNN/view?usp=sharing

**Comment by Muddz** [comment]
@samanzamani Did you manage to get it to work?

**Comment by samanzamani** [comment]
@Muddz your sample completely work. I don't know what the problem in my project

**Comment by kannasaikiran** [comment]
please add this to the gradle properties 

android.useAndroidX=true
android.enableJetifier=true
