### ISSUE TITLE
attr/radius already defined

### ISSUE THREAD

**Issue by alexwyattdev** [Muddz/StyleableToast#38]
If possible, rename the radius into toastRadius or something in attr.xml, so the projects can be built, probably in the new Android libraries 28.0.0 maybe there is a conflict.

**Comment by Muddz** [comment]
Hi and thanks for the notice. The library has targetSDK 28 and the dependency `implementation 'com.android.support:appcompat-v7:28.0.0'`

So it is up to date. But the `radius` attribute is probably conflicting with other libraries with same attribute name. I should make a prefix on all attriubtes to avoid further issues with it.

Can you tell me which library is conflicting with it?

**Comment by alexwyattdev** [comment]
Sorry, I don't know, I tried many things at once today when I tried to come up with a solution, ended up reverting back to a previous version (2.0.1) so I missed getting the culptrit one exactly.

**Comment by Muddz** [comment]
I will look at a fix in the weekend
