### ISSUE TITLE
Toast Length Issue

### ISSUE THREAD

**Issue by vishnu8742** [Muddz/StyleableToast#43]
Toast Length LONG is lasting only for 2 seconds. How to Increase Toast Length to maximum 5- 8 seconds.

**Comment by Muddz** [comment]
Hi @vishnu8742 . StyleableToast is based on the `Toast` class.  a toast can only have two durations the Long and Short and these are set by flags ìnt` flags.  See more answers here for deeper understanding: https://stackoverflow.com/questions/2220560/can-an-android-toast-be-longer-than-toast-length-long
