### ISSUE TITLE
How to add drop shadow to toast

### ISSUE THREAD

**Issue by afrishberg** [Muddz/StyleableToast#45]
I saw in SO post this example
https://stackoverflow.com/a/39591755/1441731

there are toast with drop shadow under them.
How can I achieve such effect?

@Muddz thanks!

**Comment by Muddz** [comment]
Hi. The shadow was in a experimental version for long time ago. It was just usage of "Elevation".
You can fork the projekt yourself and add the `elevtion` to the `LinearLayout` of the toast
