### ISSUE TITLE
 'tools:replace="android:appComponentFactory"'

### ISSUE THREAD

**Issue by Kaiwen20111998** [Muddz/StyleableToast#48]
Hello Muddz, 
Greetings. I'm trying to use your tool in my project with Android 9, but I cannot because exist a conflict between your tool and my SDK version. What can I do? 

Thank you.
Sincerely, Kevin.

**Comment by Muddz** [comment]
@Kaiwen20111998 It looks like a conflict between AndroidX package and the support packages.
Please take a look at this thread and try some of the suggestions: https://stackoverflow.com/questions/52135251/manifest-merger-fails-for-appcomponentfactory
