### ISSUE TITLE
More Methods Required

### ISSUE THREAD

**Issue by hshrimali** [Muddz/StyleableToast#5]
It would be better if other properties of Toast also like setGravity(), cancel(), etc. can be added just to make your StyleableToast complete in all manner.

**Comment by Muddz** [comment]
Hi and thanks for your suggestion. The cancel() has already been requested. It will be updated today hopefully!


________________________________
Fra: Himanshu Shrimali <notifications@github.com>
Sendt: 17. februar 2017 00:12
Til: Muddz/StyleableToast
Cc: Subscribed
Emne: [Muddz/StyleableToast] More Methods Required (#5)


It would be better if other properties of Toast also like setGravity(), cancel(), etc. can be added just to make your StyleableToast complete in all manner.

**Comment by hshrimali** [comment]
Thanks to you for all these features !! These are helping me a lot in improving UI of my app.

**Comment by Muddz** [comment]
I'm glad to hear that. If you have made any cool toast, feel free to send me a screenshot of it if you want it to appear under the CASES section in the github Readme


________________________________
Fra: Himanshu Shrimali <notifications@github.com>
Sendt: 19. februar 2017 17:14
Til: Muddz/StyleableToast
Cc: Muddii; Comment
Emne: Re: [Muddz/StyleableToast] More Methods Required (#5)


Thanks to you for all these features !! These are helping me a lot in improving UI of my app.

**Comment by hshrimali** [comment]
Okay so here are some toasts that I created using your work.

![screenshot_20170220-002243_1](https://cloud.githubusercontent.com/assets/17125712/23105446/613fc406-f705-11e6-9215-13594f5d6e83.jpg)
![screenshot_20170220-002850_1](https://cloud.githubusercontent.com/assets/17125712/23105445/613f40d0-f705-11e6-9eeb-277454b215b6.jpg)
![screenshot_20170220-002904_1](https://cloud.githubusercontent.com/assets/17125712/23105447/61a334fa-f705-11e6-9a2b-0d84d641e2f3.jpg)
