### ISSUE TITLE
Can't find 2.2.2

### ISSUE THREAD

**Issue by mcsong** [Muddz/StyleableToast#50]
Hello, 
I can't find 2.2.2 binary. 
Can you deploy 2.2.2 version to any mvn repository, please? 

Thank you

**Comment by Muddz** [comment]
Hi. 2.2.2 is published on `jCenter` make sure to include the repository dependency `jCenter()` in the gradle file (app level)

**Comment by mcsong** [comment]
Hi, 
jCenter has 2.2.2, but it's id are different. 
compile 'StyleableToast:styleabletoast:2.2.2'
and github's comments are implementation 'com.muddzdev:styleabletoast:2.2.2' . 
So, it's make an issue for updating to the 2.2.2.

Thanks

**Comment by Muddz** [comment]
Just remove the `compile 'StyleableToast:styleabletoast:2.2.2'` and paste this 
`implementation 'com.muddzdev:styleabletoast:2.2.2' `

**Comment by mcsong** [comment]
I'm still having problem with 'com.muddzdev:styleabletoast:2.2.2'
But, 'com.github.Muddz:StyleableToast:2.2.2' works well. 
This is buildscript repositories block in my build.xml of app project. 

buildscript {
    repositories {
        jcenter()
        google()
        maven { url "https://jitpack.io" }
        maven { url "http://maven.jahia.org/maven2/" }
        maven { url "http://dl.bintray.com/pnaleks/pnapp/" }
        maven { url 'https://maven.fabric.io/public' }
    }

    dependencies {
        classpath 'com.android.tools.build:gradle:3.4.0'

        // https://docs.fabric.io/android/changelog.html#fabric-gradle-plugin
        classpath 'io.fabric.tools:gradle:1.29.0'
    }
}

And, can you check this url for checking aar files are uploaded? 

https://bintray.com/muddz/maven/StyleableToast/2.2.2#files/com%2Fmuddzdev%2Fstyleabletoast
https://bintray.com/muddz/maven/StyleableToast/2.2.2#files/StyleableToast%2Fstyleabletoast%2F2.2.2

Thanks

**Comment by Muddz** [comment]
Hi. It has been corrected now. There was an error in my dependency "group name". It should work now with  `implementation 'com.muddzdev:styleabletoast:2.2.2'`

**Comment by mcsong** [comment]
It works well.
Thank you.
