### ISSUE TITLE
There is no vertical position

### ISSUE THREAD

**Issue by abduroid** [Muddz/StyleableToast#55]
If gravity set, it shows toast only in center. And changes horizontal position as one set in code with .gravity() method. Android built-in toast can be placed anywhere

**Comment by Muddz** [comment]
The gravity of the toast can be set with to the Top, Bottom and Center with:

        new StyleableToast.Builder(this)
                .gravity(Gravity.TOP)
                .show();
        
        new StyleableToast.Builder(this)
                .gravity(Gravity.CENTER)
                .show();

And for Bottom just don't set any gravity.

Currently there is no support for other positions other than these 3.

**Comment by abduroid** [comment]
> The gravity of the toast can be set with to the Top, Bottom and Center with:
> 
> ```
>     new StyleableToast.Builder(this)
>             .gravity(Gravity.TOP)
>             .show();
>     
>     new StyleableToast.Builder(this)
>             .gravity(Gravity.CENTER)
>             .show();
> ```
> 
> And for Bottom just don't set any gravity.
> 
> Currently there is no support for other positions other than these 3.

And how to display toast little bit higher

**Comment by Muddz** [comment]
It's not possible because the code for it has not been implemented. I will look into this feature-requests when I have time for it. Right now my priorities is on other projects. I'm sorry
