### ISSUE TITLE
Show time duration 

### ISSUE THREAD

**Issue by malekiamir** [Muddz/StyleableToast#56]
I would like to set show time duration to the toast, but I can't find anything related.

**Comment by Muddz** [comment]
You can not set a custom or specific time duration. Android internally can only accept LONG (3500 ms) or SHOT (2500 ms).

Use the predefined values:

 new StyleableToast
                .Builder(context)
                .text("Hello world!")
                .textColor(Color.WHITE)
                .setDuration(Toast.LENGTH_LONG) //or Toast.LENGTH_SHORT
                .backgroundColor(Color.BLUE)
                .show();
