### ISSUE TITLE
Drawable as Background

### ISSUE THREAD

**Issue by v1nc** [Muddz/StyleableToast#59]
Since StyleableToast is a LinearLayout, shouldnt it be possible to set the background drawable, e.g. to a gradient like this ?
```
toast.setBackground(getApplicationContext().getDrawable(R.drawable.gradient));
```
or
```
toast.setBackgroundResource(R.drawable.gradient);
```

**Comment by Muddz** [comment]
@v1nc Yes it should be. It would be a nice addition, but not something I would work on further more.
