### ISSUE TITLE
cancel method not available when using builder

### ISSUE THREAD

**Issue by Kxtreme** [Muddz/StyleableToast#62]
When creating the toast via the Builder method it returns a Builder and it doesn't contain a cancel method.

**Comment by Muddz** [comment]
@Kxtreme Yes I just confirmed it with my own checking. I will make sure to implement it in the next update. Probably in the weekend

**Comment by Muddz** [comment]
This fix is available in the newest version: ` implementation 'com.muddzdev:styleabletoast:2.3.0'`

An `cancel()` and `build()` method  has been added when using the builder.
