### ISSUE TITLE
Detect if toast is showing

### ISSUE THREAD

**Issue by xcesaralejandro** [Muddz/StyleableToast#63]
Is it possible to add a method to detect if there is already a toast displayed on the screen?

Sometimes the toast is dependent on an event such as the button click, if the button is clicked many times, many toasts will be displayed, which is somewhat annoying.
Adding variables to prevent that behavior makes the code dirty.

Example: (The method name is only for example, my English is very bad)

`StyleableToast.isDisplaying(Some identifier)`

`StyleableToast.makeText(ctx, message, Toast.LENGTH_SHORT, R.style.infoToast, "toast-1").show();`
`StyleableToast.isDisplaying("toast-1")`

```
if(!StyleableToast.isDisplaying("toast-1")){
    StyleableToast.makeText(ctx, message, Toast.LENGTH_SHORT, R.style.infoToast, "toast-1").show();
}
```

**Comment by Muddz** [comment]
Hi there. Toast dosen't have any method for checking if a Toast is currently being displayed.
In the newest version `implementation 'com.muddzdev:styleabletoast:2.3.0'` you can use the `cancel()` method which will cancel any ongoing toast before calling `show()`

**Comment by sdex** [comment]
Should be possible by using https://github.com/square/curtains
