### ISSUE TITLE
Support custom duration

### ISSUE THREAD

**Issue by Xorok** [Muddz/StyleableToast#8]
One of the biggest limitations with regular Toasts is the limited duration time (Only two states available). As far as I can see, this could be easily fixed in this library by allowing other durations in the withDuration() method (for the builder).

```
public StyleableToast.Builder withDuration(int duration) {
    if(duration == 1 || duration == 0) {
        this.length = duration;
    }

    return this;
}
```

**Comment by Muddz** [comment]
Its not possible to extend the life of a toast since it is a build in boolean flag. it can either be short or long.
A another idea would be to create a completely new Toast from scratch that has nothing to do with the `Toast` class itself in android. But this library builds on the existing `Toast`
